[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.100"
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.3.4", features = ["wasm_js"] }
rand = "0.9.2"
wasm-bindgen = "0.2.106"
web-sys = "0.3.83"
